FROM python:3.12-slim

ENV PYTHONBUFFERED True

# Set the working directory
WORKDIR /usr/src/app

# Install dependencies
COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY ./src ./src

EXPOSE 4000

# Start the server
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "4000", "--proxy-headers"]