apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fastapi-ml-model-service
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/sportlink-b061c/fastapi-ml-model/fastapi-ml-model:latest
          env:
          ports:
            - containerPort: 4000